<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Ecommerce\EcommerceBundle\DataFixtures\ORM\CommandesData' shared autowired service.

return $this->services['Ecommerce\EcommerceBundle\DataFixtures\ORM\CommandesData'] = new \Ecommerce\EcommerceBundle\DataFixtures\ORM\CommandesData();
