<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'maker.auto_command.make_entity' shared service.

$a = ${($_ = isset($this->services['maker.file_manager']) ? $this->services['maker.file_manager'] : $this->load(__DIR__.'/getMaker_FileManagerService.php')) && false ?: '_'};
$b = ${($_ = isset($this->services['maker.generator']) ? $this->services['maker.generator'] : $this->load(__DIR__.'/getMaker_GeneratorService.php')) && false ?: '_'};

$this->services['maker.auto_command.make_entity'] = $instance = new \Symfony\Bundle\MakerBundle\Command\MakerCommand(new \Symfony\Bundle\MakerBundle\Maker\MakeEntity($a, ${($_ = isset($this->services['maker.doctrine_helper']) ? $this->services['maker.doctrine_helper'] : $this->load(__DIR__.'/getMaker_DoctrineHelperService.php')) && false ?: '_'}, $this->targetDirs[3], $b), $a, $b);

$instance->setName('make:entity');

return $instance;
