<?php

namespace Utilisateurs\UtilisateursBundle\Repository;

/**
 * PagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateursRepository extends \Doctrine\ORM\EntityRepository
{
}
