pages_pages_adminPages:
    resource: "@PagesPagesBundle/Resources/config/routingAdmin.yml"
    prefix:   /admin/pages/

page:
    path:     /page/{id}
    defaults: { _controller: PagesPagesBundle:Pages:page }
