<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'app.search' shared autowired service.

return $this->services['app.search'] = new \AppBundle\Form\Type\SearchFormType();
