<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'setNewFacture' shared autowired service.

return $this->services['setNewFacture'] = new \Ecommerce\EcommerceBundle\Services\GetFacture($this);
