<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (!class_exists(\Container5pwtlgd\appDevDebugProjectContainer::class, false)) {
    require __DIR__.'/Container5pwtlgd/appDevDebugProjectContainer.php';
}

if (!class_exists(appDevDebugProjectContainer::class, false)) {
    class_alias(\Container5pwtlgd\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container5pwtlgd\appDevDebugProjectContainer();
